#!/bin/bash
#Descrição: Script para auto inicialização do Apache Tomcat

### BEGIN INIT INFO
# Provides:          tomcat_autostart
# Required-Start:   
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts Apache_tomcat at boot time
# Description:       Enable service provided by tomcat_auto
### END INIT INFO

# Definição dos caminhos do software
user='dspace'
log="/home/$user/apache-tomcat/logs/actions.log"
temp="/home/$user/.tomcat.temp"
bin="/home/$user/apache-tomcat/bin"

case "$1" in
	'start')
		echo "SERVIDOR TOMCAT INICIADO  | `date` : `id -nu`" >> $log
		echo "------------------------------------------------------------" >> $log
		$bin/startup.sh >> $log
		touch $temp
		echo "[ON] Servidor Tomcat iniciado"
		;;

	'stop')
		echo "SERVIDOR TOMCAT DESLIGADO  | `date` : `id -nu`" >> $log
		echo "------------------------------------------------------------" >> $log
		$bin/shutdown.sh >> $log
		rm -f $temp
		echo "[OFF] Servidor Tomcat desligado."
		;;

	'restart')
		echo "SERVIDOR TOMCAT REINICIADO  | `date` : `id -nu`" >> $log
		echo "------------------------------------------------------------" >> $log
		$bin/shutdown.sh >> $log
		rm -f $temp
		$bin/startup.sh >> $log
		touch $temp
		echo "[RESTARTED] Servidor Tomcat reiniciado."
		;;

	'cleanlog')
		echo "ARQUIVO DE LOG REINICIADO  | `date` : `id -nu`" > $log
		;;

	'running')
		if [ -e $temp ] ; then
			echo "[ON] O Servidor Tomcat está executando"
		else
			echo "[OFF] O Servidor Tomcat não está executando"
		fi
		;;

	'log')
		less $log
		;;

	*)
		echo "Use 'service tomcat' com um dos argumentos: [ start | stop | restart | running | log ]"
		RETVAL=1
esac

exit $RETVAL
